# Variables, Data Types, and Operators

In [1]:
# integer variable 
a = 10
# string variable
b = "Neural Networks"
# float variable
c = 3.14 
# list variable 
d = [1,2,3,4,5]
# dictionary variable
e = {'AI': 'Artificial Intelligence', 'NN': 'Neural Networks'}

# Loops and Control Structures

In [3]:
# if-else
a = 5
if a>0:
    print("Positive number")
else:
    print("Negative number")

Positive number


In [4]:
# for loop
for i in range(5):
    print(i)

0
1
2
3
4


In [5]:
# while loop
a = 5
while a > 0:
    print(a)
    a -= 1

5
4
3
2
1


# Functions

In [1]:
#Function to find the square of a number 
def square(x):
    return x*x


In [6]:
import numpy as np
numpy_array = np.array([1,2,3,4,5])
print(numpy_array)

[1 2 3 4 5]


In [9]:
import numpy as np
x1=1
x2=2
w1=3
w2=4
inputs = np.array([x1, x2])
weights = np.array([w1, w2])
output = np.matmul(inputs, weights)
print(output)

11


In [10]:
import numpy as np

# Create a numpy array
A = np.array([1, 2, 3, 4, 5])

# Perform an operation on the array
B = A + 2
print(B)

[3 4 5 6 7]


In [11]:
A = np.array([[1, 2, 3], [4, 5, 6]])

# Compute the sum over all elements
print(np.sum(A))              # Output: 21

# Compute the sum along the first axis (rows)
print(np.sum(A, axis=0))      # Output: array([5, 7, 9])

# Compute the sum along the second axis (columns)
print(np.sum(A, axis=1))      # Output: array([ 6, 15])



21
[5 7 9]
[ 6 15]


In [12]:
# Create two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Perform dot product
dot_product = np.dot(a, b)
print(dot_product)  # Output: 32


32


In [13]:
a = np.array([1, 2, 3])

# Apply the exponential function
exp_a = np.exp(a)

print(exp_a)  # Output: [ 2.71828183  7.3890561  20.08553692]


[ 2.71828183  7.3890561  20.08553692]


In [14]:
# Generate a 1D array of random numbers
random_array = np.random.rand(3)

print(random_array)  # Output: [0.42057158 0.70547945 0.1818582 ]


[0.45016624 0.47272764 0.89726138]


In [15]:
import numpy as np
import time

# How to create a python list and a numpy array
py_list = list(range(1000000))
np_array = np.array(range(1000000))

# Multiplying elements in python list by 2
start_time = time.time() 
list_mult = [2 * i for i in py_list]
end_time = time.time()
print("Time taken by Python list: ", end_time - start_time)

# Multiplying elements in numpy array by 2
start_time = time.time()
array_mult = np_array * 2
end_time = time.time()
print("Time taken by Numpy array: ", end_time - start_time)


Time taken by Python list:  0.043999433517456055
Time taken by Numpy array:  0.0010004043579101562


In [16]:
import numpy as np

# define two arrays with different shapes
a = np.array([1, 2, 3])
b = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

# apply broadcasting
c = a + b
print(c)


[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]
